circleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,17 +35,13 @@ jobs:
       - run:
           name: Build Docker Image (book-store)
           command: |
-            cd $PROJECT_DIR
-            docker build -t zengemily79/book-store:$VERSION .
-      - run:
-          name: Login to Docker Hub
-          command: |
-            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-      - run:
-          name: Push Docker Image (book-store)
-          command: |
-            cd $PROJECT_DIR
-            docker push zengemily79/book-store:$VERSION
+            source $BASH_ENV
+            if [ -z "$VERSION" ]; then
+              echo "ERROR: VERSION is empty!"
+              exit 1
+            fi
+            echo $VERSION
+
 
 workflows:
   version: 2
